title: Zixuan Jiang's Homepage
page-top-title: Zixuan Jiang
top-section-bg-text: Artificial Intelligence
home-subtitle: Zixuan Jiang&ensp;|&ensp;蒋梓轩
copyright-text: '&copy; Zixuan Jiang 2025-. All Rights Reserved.'
