title: Zixuan Jiang's Homepage
page-top-title: AnXMuy | Zixuan Jiang
top-section-bg-text: TRAIN, INFER, TRANSCEND...
home-subtitle: Andrew&ensp;|&ensp;蒋梓轩
copyright-text: '&copy; Zixuan Jiang 2025-. All Rights Reserved.'
