#!/usr/bin/env python3
"""Batch-generate per-paper analysis markdown using OpenAI-compatible API.

Inputs:
- PDFs under ../bot_memory
- API settings from env vars

Outputs:
- knowledge/papers/<paper_name>.md
- knowledge/papers/INDEX.md
"""

from __future__ import annotations

import json
import os
import re
import time
from pathlib import Path
from typing import List
from urllib import request, error

from pypdf import PdfReader

REPO_ROOT = Path(__file__).resolve().parents[1]
BOT_MEMORY_DIR = REPO_ROOT.parent / "bot_memory"
OUTPUT_DIR = REPO_ROOT / "knowledge" / "papers"

API_BASE_URL = os.environ.get("PAPER_API_BASE_URL", "https://api.deepseek.com")
API_MODEL = os.environ.get("PAPER_API_MODEL", "deepseek-v4-flash")
API_KEY = os.environ.get("PAPER_API_KEY", "")

MAX_PAGES_PER_PDF = int(os.environ.get("PAPER_MAX_PAGES", "16"))
MAX_CHARS_PER_PDF = int(os.environ.get("PAPER_MAX_CHARS", "80000"))
REQUEST_TIMEOUT = int(os.environ.get("PAPER_TIMEOUT", "240"))

PROMPT_TEMPLATE = """你是一个人工智能领域的博士生。你的角色是高效，深入的论文分析师。你的目标是完整仔细阅读论文，深入理解论文，并生成完整总结分析，以便学习和在研究中借鉴。

请仔细阅读论文（用户提供的文本，文件）后，严格依据下面的任务框架进行总结和分析：

1. 翻译摘要原文
2. 动机与相关工作：
    1. 这篇文章针对什么任务（或以什么任务为载体）？
    2. 现有方法有哪些？痛点/不足是什么？具体指出局限性。
    3. 作者的Motivation是什么？阐述背后的逻辑链。
    4. 论文的研究假设是什么？
    5. 用有序列表形式总结这篇文章做了什么工作（如果论文Introduction结尾有总结，直接翻译）
3. 方法：给出清晰的方法流程总结（pipeline），逐步解释输入→处理→输出。必须讲清楚每一步的具体操作和技术细节。这一步必须非常细致，这是用户的主要阅读目标。
    1. 对于论文给出的每张图（尤其是主图），先输出图注，进行仔细分析与解释
    2. 如果涉及模型结构，请描述每个模块的功能与作用，以及它们如何协同工作。
    3. 对于每个公式，请先输出公式用通俗的语言解释公式的意义与作用，后详细解释公式的每个参数以及维度。
    4. 如果有算法，先用通俗的语言解释算法流程，解释意义与作用，后举一个实例，解释算法的执行流程。
4. 创新点：
    1. 本方法和现有主流方法相比，有什么本质不同？
    2. 方法的创新点在哪里？明确指出贡献点。
    3. 分析方法的适用范围
5. 实验：
    1. 方法的主实验是什么？详细描述实验设定（包括数据集，预处理，和哪些方法对比等），实验结果（评价指标与结果）
    2. 方法的消融实验做了哪些，分别针对什么问题，实验结果如何？
    3. 是否有局限性（比如泛化能力、计算开销、对特定数据的依赖）？指出论文中承认或隐含的不足。
6. 总结：用一句话概括这个方法的核心思想（不超过20字）。

关键规则:

1. 语言风格: 专业、严谨、逻辑性强，完全采用中文（除专业术语）进行回复。
2. 回复结构: 严格按照上述分析框架，使用清晰的分段和编号。
3. 数据来源: 所有分析必须基于用户提供的论文内容。如果用户未提供论文内容，则请要求用户上传PDF或提供论文文本/摘要。对于自行分析的部分，需用<subject>标明
4. 聚焦核心: 重点解析方法与实验部分，避免过度讨论引言和结论。
5. 输出要求: 用户可能不再阅读论文具体内容，而是只阅读你提供的信息。

请开始分析以下论文文本（可能是部分提取，若信息缺失请明确写出<subject>推断边界）：

"""


def slugify(name: str) -> str:
    name = re.sub(r"\.pdf$", "", name, flags=re.IGNORECASE)
    name = re.sub(r"[^a-zA-Z0-9\u4e00-\u9fff._-]+", "_", name)
    return name.strip("_") or "paper"


def extract_pdf_text(pdf_path: Path) -> str:
    reader = PdfReader(str(pdf_path))
    pages = reader.pages[:MAX_PAGES_PER_PDF]
    parts: List[str] = []
    for page in pages:
        txt = page.extract_text() or ""
        if txt:
            parts.append(txt)
    text = "\n".join(parts)
    text = text[:MAX_CHARS_PER_PDF]
    return text


def call_chat_api(content: str) -> str:
    if not API_KEY:
        raise RuntimeError("PAPER_API_KEY is empty")

    url = API_BASE_URL.rstrip("/") + "/chat/completions"
    payload = {
        "model": API_MODEL,
        "messages": [
            {"role": "system", "content": "你是严谨的人工智能论文分析助手。"},
            {"role": "user", "content": PROMPT_TEMPLATE + "\n" + content},
        ],
        "thinking": {"type": "enabled"},
        "reasoning_effort": "high",
        "stream": False,
    }

    data = json.dumps(payload).encode("utf-8")
    req = request.Request(
        url,
        data=data,
        method="POST",
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {API_KEY}",
        },
    )
    try:
        with request.urlopen(req, timeout=REQUEST_TIMEOUT) as resp:
            obj = json.loads(resp.read().decode("utf-8", errors="ignore"))
    except error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="ignore")
        raise RuntimeError(f"HTTP {e.code}: {detail}") from e

    return obj.get("choices", [{}])[0].get("message", {}).get("content", "")


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    pdfs = sorted(BOT_MEMORY_DIR.glob("*.pdf"))
    if not pdfs:
        raise RuntimeError(f"No PDF files found in {BOT_MEMORY_DIR}")

    index_lines = ["# Paper Analysis Index", "", "Generated by scripts/generate_paper_analysis.py", ""]

    for pdf in pdfs:
        print(f"[INFO] Processing {pdf.name}")
        text = extract_pdf_text(pdf)
        if not text.strip():
            print(f"[WARN] Empty extracted text for {pdf.name}, skipped")
            continue

        analysis = call_chat_api(text)
        if not analysis.strip():
            print(f"[WARN] Empty model output for {pdf.name}, skipped")
            continue

        out_name = slugify(pdf.name) + ".md"
        out_file = OUTPUT_DIR / out_name
        out_file.write_text(
            f"# {pdf.name} 分析\n\n"
            f"- Source PDF: `{pdf}`\n"
            f"- Model: `{API_MODEL}`\n"
            f"- Generated at: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n"
            f"{analysis}\n",
            encoding="utf-8",
        )
        print(f"[OK] Wrote {out_file}")
        index_lines.append(f"- [{out_name}](./{out_name})")

    (OUTPUT_DIR / "INDEX.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    print(f"[OK] Wrote {(OUTPUT_DIR / 'INDEX.md')}")


if __name__ == "__main__":
    main()
